### ISSUE TITLE
installation error with step python3 manage.py migrate

### ISSUE THREAD

**Issue by mightynico** [pytition/Pytition#325]
I try to install the project to my debian 12 VM. So I follow your instructions. I hope I  installed all depedencies but I crash with the step python3 manage.py migrate.

This is my output in my CLI:

(pytition_venv) root@attac-petition:/var/www/petition/www/pytition/pytition# python3 manage.py migrate
Traceback (most recent call last):
  File "/var/www/petition/www/pytition/pytition/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/petition/pytition_venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/var/www/petition/pytition_venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 382, in execute
    settings.INSTALLED_APPS
  File "/var/www/petition/pytition_venv/lib/python3.11/site-packages/django/conf/__init__.py", line 102, in __getattr__
    self._setup(name)
  File "/var/www/petition/pytition_venv/lib/python3.11/site-packages/django/conf/__init__.py", line 89, in _setup
    self._wrapped = Settings(settings_module)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/petition/pytition_venv/lib/python3.11/site-packages/django/conf/__init__.py", line 217, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/var/www/petition/www/pytition/pytition/pytition/settings/config.py", line 41
    STATIC_ROOT = /var/www/petition/www/static
                  ^
SyntaxError: invalid syntax

What can I do? 
Thanks

**Comment by fallen** [comment]
Hello @mightynico 

The issue is that you need to put quotes or double quotes around the strings in your setting file:

```
STATIC_ROOT = '/var/www/petition/www/static'
```

Another thing: don't install using the `root` user, create a non-priviledged `pytition` user.

**Comment by mightynico** [comment]
Thanks, I will test it
